### ISSUE TITLE
Panic in main.rs when calling cosmic-screenshot

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-screenshot#10]
All of a sudden my Fedora COSMIC image can't use cosmic-screenshot. I run it from the terminal (because I don't have printscr on my laptop (see: https://github.com/pop-os/cosmic-comp/pull/310)

and I get a panic:

thread 'main' panicked at src/main.rs:71:10:
failed to receive screenshot response: Response(Cancelled)

Everything should be built to master as of a few hours ago.

**Comment by joshuamegnauth54** [comment]
`cosmic-screenshot` should work with different portals as long as they provide the screenshot end point thingy. I tried it with GNOME.

Just a hunch, but what happens when you run it like so:

`cosmic-screenshot --interactive=false --modal=false`

Check `~/Pictures` afterwards.

**Comment by jacobgkau** [comment]
I'm getting this issue on Pop!_OS 22.04 today after installing the latest updates. The PrtSc key and the plain command don't work.

```
jacob@serw13:~$ cosmic-screenshot
thread 'main' panicked at src/main.rs:71:10:
failed to receive screenshot response: Response(Cancelled)
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Running with `--interactive=false --modal=false` does work to capture the entire screen.

**Comment by asjur** [comment]
On arch here but workaround above doesn't work. Same exact issue.
