### ISSUE TITLE
cosmic-screenshot doesn't work 

### ISSUE THREAD

**Issue by romanstingler** [pop-os/cosmic-screenshot#66]
CachyOS Repo `cosmic-screenshot 1.0.0.alpha.2-2` 

```
~[101] ❯ RUST_BACKTRACE=full cosmic-screenshot                                                                                                                                                       17:59
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.32"))), reply-serial: 17, body: Signature("s") }))
stack backtrace:
   0:     0x64c9b41637e9 - <unknown>
   1:     0x64c9b4189fdb - <unknown>
   2:     0x64c9b41602ff - <unknown>
   3:     0x64c9b4164941 - <unknown>
   4:     0x64c9b416461c - <unknown>
   5:     0x64c9b4165001 - <unknown>
   6:     0x64c9b4164e67 - <unknown>
   7:     0x64c9b4163cd9 - <unknown>
   8:     0x64c9b4164af3 - <unknown>
   9:     0x64c9b41884e2 - <unknown>
  10:     0x64c9b4188996 - <unknown>
  11:     0x64c9b3efc4fb - <unknown>
  12:     0x64c9b3faf811 - <unknown>
  13:     0x64c9b3f9547b - <unknown>
  14:     0x64c9b3fafb8d - <unknown>
  15:     0x64c9b3f9582b - <unknown>
  16:     0x64c9b3f9e8dc - <unknown>
  17:     0x64c9b3f8d973 - <unknown>
  18:     0x64c9b3f7a063 - <unknown>
  19:     0x64c9b3fa2989 - <unknown>
  20:     0x64c9b415ac3c - <unknown>
  21:     0x64c9b3f8da4c - <unknown>
  22:     0x7ee6937a11ce - <unknown>
  23:     0x7ee6937a128a - __libc_start_main
  24:     0x64c9b3ea1d45 - <unknown>
  25:                0x0 - <unknown>
  ```

**Comment by nevdelap** [comment]
@romanstingler Not a fix, but a workaround, if you switch to `cosmic-greeter` it works.

**Comment by rediskap** [comment]
Same problem!
cosmic-screenhot does not work. Inference:
```[redis@dn7 ~]$ cosmic-screenshot
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("Не существует интерфейса “org.freedesktop.portal.Screenshot” на объекте по пути /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.41"))), reply-serial: 17, body: Signature("s") }))
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```
 I tried the advice cosmic-greeter. Inference:
```[redis@dn7 ~]$ cosmic-greeter
[2024-12-11T19:19:48Z WARN  cosmic_greeter::logind] logind error: org.freedesktop.login1.NoSessionForPID: PID 1890 does not belong to any known session
[redis@dn7 ~]$ cosmic-screenshot
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("Не существует интерфейса “org.freedesktop.portal.Screenshot” на объекте по пути /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.41"))), reply-serial: 17, body: Signature("s") }))
stack backtrace:
note: Some details are omitted
, run with `RUST_BACKTRACE=full` for a verbose backtrace.```
At RUST_BACKTRACE=full cosmic-screenshot
```hread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("Не существует интерфейса “org.freedesktop.portal.Screenshot” на объекте по пути /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.41"))), reply-serial: 17, body: Signature("s") }))
stack backtrace:
   0:     0x6491539b3418 - <unknown>
   1:     0x6491538412a3 - <unknown>
   2:     0x6491539af953 - <unknown>
   3:     0x6491539b3262 - <unknown>
   4:     0x6491539b41f0 - <unknown>
   5:     0x6491539b4036 - <unknown>
   6:     0x6491539b47d2 - <unknown>
   7:     0x6491539b466a - <unknown>
   8:     0x6491539b38d9 - <unknown>
   9:     0x6491539b42fc - <unknown>
  10:     0x64915383fab0 - <unknown>
  11:     0x64915383feb6 - <unknown>
  12:     0x6491538a7655 - <unknown>
  13:     0x64915394e364 - <unknown>
  14:     0x64915395e75f - <unknown>
  15:     0x64915394e558 - <unknown>
  16:     0x64915395eaf4 - <unknown>
  17:     0x649153939c5c - <unknown>
  18:     0x649153927151 - <unknown>
  19:     0x64915391d0d6 - <unknown>
  20:     0x64915395806c - <unknown>
  21:     0x6491539aa887 - <unknown>
  22:     0x649153927244 - <unknown>
  23:     0x7705aaa56e08 - <unknown>
  24:     0x7705aaa56ecc - __libc_start_main
  25:     0x6491537d87b5 - <unknown>
  26:                0x0 - [<unknown>```](url)
