### ISSUE TITLE
[BUG] Cosmic Screenshot crashes when started

### ISSUE THREAD

**Issue by Alfatango12** [pop-os/cosmic-screenshot#70]
When I try to open this tool using `cosmic-screenshot` from terminal in won't open and it seas: `thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("Interfaccia «org.freedesktop.portal.Screenshot» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.18"))), reply-serial: 17, body: Signature("s") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

If I launch it with `RUST_BACKTRACE=full` it seas 
`thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("Interfaccia «org.freedesktop.portal.Screenshot» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.18"))), reply-serial: 17, body: Signature("s") }))
stack backtrace:
   0:     0x5ac193adb848 - <unknown>
   1:     0x5ac193967edb - <unknown>
   2:     0x5ac193ad7c83 - <unknown>
   3:     0x5ac193adc9fa - <unknown>
   4:     0x5ac193adc647 - <unknown>
   5:     0x5ac193add0e9 - <unknown>
   6:     0x5ac193adcff7 - <unknown>
   7:     0x5ac193adbd09 - <unknown>
   8:     0x5ac193adcc84 - <unknown>
   9:     0x5ac193966663 - <unknown>
  10:     0x5ac193966af6 - <unknown>
  11:     0x5ac1939cd690 - <unknown>
  12:     0x5ac193a35314 - <unknown>
  13:     0x5ac193a2bd1f - <unknown>
  14:     0x5ac193a35508 - <unknown>
  15:     0x5ac193a2c0b4 - <unknown>
  16:     0x5ac193a5349c - <unknown>
  17:     0x5ac193a5f1e1 - <unknown>
  18:     0x5ac193a4c096 - <unknown>
  19:     0x5ac193a2e10c - <unknown>
  20:     0x5ac193ad2785 - <unknown>
  21:     0x5ac193a5f2d4 - <unknown>
  22:     0x7853200b8e08 - <unknown>
  23:     0x7853200b8ecc - __libc_start_main
  24:     0x5ac1938fe805 - <unknown>
  25:                0x0 - <unknown>`

The version of the tool is: cosmic-screenshot 1.0.0.alpha.3-1

**Comment by Alfatango12** [comment]
Closing because it just fixed itself when powering on my PC this morning after powering it off yesterday evening night. BTW thanks to the cosmic team and keep up with the great work!
